# Generated by Django 3.1.2 on 2021-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0006_auto_20210126_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('f', 'free'), ('p', 'paid')], default='f', max_length=1),
        ),
    ]
