# Generated by Django 3.1.2 on 2020-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0002_event_order_promotion_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='empty', max_length=80),
        ),
    ]
