# Generated by Django 3.1.2 on 2021-01-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pages', '0004_auto_20201029_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
